#!/usr/bin/env python

from __future__ import print_function

import sys
import os
# import vlc
import subprocess
import glob

# https://stackoverflow.com/questions/20021457/playing-mp3-song-on-python

def playmp3(filename):
    print("Playing file", filename)
    subprocess.Popen(['mpg123', '-q', filename]).wait()

def playfolder(filename):
    print("Playing folder", filename)
    files = glob.glob(filename + "/*")
    for f in sorted(files, key=os.path.getmtime):
        # print("open", f)
        playmp3(f)

filename = sys.argv[1]
if os.path.isfile(filename):
    playmp3(filename)
elif os.path.isdir(filename):
    playfolder(filename)
else:
    raise FileNotFoundError    
