#!/usr/bin/python3

from os import chdir
from subprocess import call

GIT_REPOS = [
    'interview-topics',
    'pangloss',
    'reading-list',
    ]
    

HOME_DIR = '/home/heitor/'

for repo in GIT_REPOS:
    repo_dir = "{}{}".format(HOME_DIR, repo)
    print("In repo", repo_dir)
    chdir(repo_dir)
    call(["git", "status"])
