(defun ackermann-peter (m n)
  (cond ((= m 0) (+ n 1))
        ((and (> m 0) (= n 0)) (ackermann-peter (- m 1) 1))
        ((and (> m 0) (> n 0)) (ackermann-peter (- m 1) (ackermann-peter m (- n 1))))
        (t (error "Unknown branch"))))
