Opt("WinWaitDelay", 50)

HotKeySet("{PAUSE}", "SummonDiz")

While 1
   Sleep(100)
WEnd
   
Func SummonDiz()
   WinActivate("(2) lo Zingarelli")
   Send("{CTRLDOWN}r{CTRLUP}")

   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
   Send("{CTRLDOWN}h{CTRLUP}")
EndFunc
